#!/bin/bash

# Apparently set -e is considered bad practice.
# A better approach, is to use something like:
#   trap 'do_something' ERR
# where do_something function will run when an error occurs
# TODO AG: Consider using trap as an alternative
# source: http://stackoverflow.com/questions/19622198/what-does-set-e-mean-in-a-bash-script
set -e

export NODE_ENV=test

if [ $# -eq 0 ]; then
  npx jest --watchAll=false --testPathPattern=.*.test.*$
else
  npx jest $@
fi
