# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run
# tests across different versions of node.
#
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: dispaccio-unit-tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Enable Corepack before setting up Node
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          cache: 'yarn'
      - run: yarn install
      - run: npm test
